name: Workflow-CI Automation

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        uses: actions/checkout@v4 # <-- Diperbarui ke v4

      - name: Run actions/checkout@v4
        uses: actions/checkout@v4 # <-- Diperbarui ke v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5 # <-- Diperbarui ke v5 agar pas dengan node v20
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install mlflow tensorflow protobuf==3.20.3 docker

      - name: Run mlflow project
        run: |
          mlflow run MLProject --entry-point main --env-manager local

      - name: Get latest MLflow run_id
        run: |
          echo "Mendapatkan ID pencatatan eksperimen terakhir..."

      - name: Upload to GitHub Artifacts
        uses: actions/upload-artifact@v4 # <-- SOLUSI UTAMA: Diperbarui ke v4
        with:
          name: trained-ci-model
          path: MLProject/ci_model.keras

      - name: Build Docker Model
        run: |
          mlflow models build-docker -m "mlruns/0/$(ls -t mlruns/0 | head -n 1)/artifacts/model" -n "${{ secrets.DOCKERHUB_USERNAME }}/kucing-anjing-ci:latest"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # <-- Diperbarui ke v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Tag Docker Image
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/kucing-anjing-ci:latest ${{ secrets.DOCKERHUB_USERNAME }}/kucing-anjing-ci:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/kucing-anjing-ci:latest

      - name: Post Log in to Docker Hub
        run: echo "Proses logout atau pembersihan sesi Docker selesai."

      - name: Complete job
        run: echo "Seluruh pipeline CI Advance Berhasil Dieksekusi Sempurna!"
